import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import { CursorProvider } from "@/components/CursorContext";
import CustomCursor from "@/components/CustomCursor";
import SiteMenu from "@/components/SiteMenu";
import TopNavBar from "@/components/TopNavBar";



const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CursorProvider>
          <CustomCursor />
          <SiteMenu />
          <TopNavBar /> 
          {children}
        </CursorProvider>
      </body>
    </html>
  );
}
